### ISSUE TITLE
non-actionable error message about non-authenticated Push

### ISSUE THREAD

**Issue by vors** [getconnect/connect-net-sdk#6]
I forgot to call `ConnectSDK.Connect.Initialize()` and had troubles trying to figure out what `NullReferenceException` from `ConnectSDK.Connect.Push()` mean.
It's better to add a separate check for non-initialized access to make error message actionable.

**Comment by mattfurness** [comment]
:+1:

**Comment by chadedrupt** [comment]
Thanks Sergei
